apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scheduled-job
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "* * * * *"
    - name: direction
      value: "input"
    - name: route
      value: /scheduled-job